"""create model Complaint

Revision ID: b02e7f179ff4
Revises: 35acfab584de
Create Date: 2023-06-27 04:29:53.366549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02e7f179ff4'
down_revision = '35acfab584de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], name='fk_complaint_announcement_id_announcement'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_complaint_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    # ### end Alembic commands ###
